// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEkrlO2yD5EOWQy8gP6KJHPp0Ls_biCLg',
    appId: '1:778147129922:web:ec4025b051375c631f1bdb',
    messagingSenderId: '778147129922',
    projectId: 'chat-app-b4154',
    authDomain: 'chat-app-b4154.firebaseapp.com',
    storageBucket: 'chat-app-b4154.appspot.com',
    measurementId: 'G-TR92L3JD8B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9zRMuuJKXdeKPkxmdQe4sYtR4LdeevRA',
    appId: '1:778147129922:android:5234da1ea99725e91f1bdb',
    messagingSenderId: '778147129922',
    projectId: 'chat-app-b4154',
    storageBucket: 'chat-app-b4154.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClK01M2QqgiobK52Tt4UNtM1ZB4gswjMU',
    appId: '1:778147129922:ios:53f23aec907d89681f1bdb',
    messagingSenderId: '778147129922',
    projectId: 'chat-app-b4154',
    storageBucket: 'chat-app-b4154.appspot.com',
    iosClientId: '778147129922-hprmlali48hpmuvn7r2k4etrinvkubh8.apps.googleusercontent.com',
    iosBundleId: 'com.example.leochat',
  );
}
